### ISSUE TITLE
full alignment and the corresponding graph

### ISSUE THREAD

**Issue by edchengg** [SapienzaNLP/unify-srl#1]
Hi,

Can you point me to the alignment? thank you!
I was wondering do you have alignment/mapping of argument roles across languages?

**Comment by andreabac3** [comment]
Hi @edchengg,
Thank you for your interest in the project.
We are working on a refactoring of the code to generate the Graph alignment and to release the mapping.

You can currently use the checkpoint to generate your alignment.

We will let you know,
Andrea Bacciu
