### ISSUE TITLE
evaluation script for cz

### ISSUE THREAD

**Issue by edchengg** [SapienzaNLP/unify-srl#2]
I was trying to run the evaluation script for cz and I got this error.

python evaluate_conll2009.py --scorer scorer_conll2009.pl --processor xlmr_ft_full_all/processor_config.json --model xlmr_ft_full_all/checkpoint_epoch\=026-val_f1\=0.9028.ckpt --config ../config/full/cz_config.json --output_dir xlmr_ft_full_all/

Evaluation on CZ
```
Traceback (most recent call last):
  File "evaluate_conll2009.py", line 114, in <module>
    if output_senses[i] != '_':
IndexError: list index out of range
```

other languages work fine. not sure what happened to this one.

**Comment by c-simone** [comment]
Unfortunately, I am not able to reproduce the issue. I am running the following command:
```bash
python srl/evaluate_conll2009.py \
  --processor checkpoints/xlmr_ft_full_all/processor_config.json \
  --model checkpoints/xlmr_ft_full_all/checkpoint_epoch=026-val_f1=0.9028.ckpt \
  --config config/full/all_config.json \
  --output_dir predictions/
```

Did you, by any chance, make any changes to `evaluate_conll2009.py`? I noticed that the line pointed out by the error is different from the original one).
