### ISSUE TITLE
1-shot data preprocessing

### ISSUE THREAD

**Issue by edchengg** [SapienzaNLP/unify-srl#3]
I was trying to replicate the results for the one shot setting but not sure which sentences are used in the training set. Can you release the data preprocessing script for the 1-shot setting? 
or
is it just following the order of the dataset and remove the sentences with replicated predicate sense?
Thank you.

**Comment by andreabac3** [comment]
Hello @edchengg, we followed your second intuition.

Kind regards,
Andrea
